const HTML_COMMENT_REGEX = /<!--[\s\S]*?-->/g
const MARKDOWN_IMAGE_REGEX = /!\[.*?\]\([^)]+\)/g
const HTML_IMAGE_REGEX = /<img[^>]*>/g
const CODE_BLOCK_REGEX = /```[\s\S]*?```/g
const ISSUE_CHECKBOX_REGEX = /^-\s*\[[x\s]\]\s*(?:\S.*)?$/gim
const BOT_FOOTER_REGEX = /^(This issue was|Generated by|View on).*$/gim
const MULTIPLE_EMPTY_LINES_REGEX = /\n{3,}/g
const TRAILING_SPACES_REGEX = /[ \t]+$/gm
const IGNORE_HEADERS = [
  'Validations',
  'Contributions',
  'Checklist',
  'Acknowledgements',
  'System Info',
  'Environment',
  'Desktop',
  'Smartphone',
  'Browsers',
].join('|')
const IGNORE_HEADER_SECTION_REGEX = new RegExp(
  `#{2,4}\\s*(${IGNORE_HEADERS})[\\s\\S]*?(?=#{2,4}\\s|$)`,
  'gi',
)

function normalizeIssueDetail(issue = {}, originIssue = {}) {
  return {
    ...issue,
    body: originIssue.body,
    assignee: originIssue.assignee,
    assignees: originIssue.assignees,
    locked: originIssue.locked,
    formatBody: formatIssueForAI(originIssue.body),
  }
}

export function normalizeIssues({ origins = [], issues = [] } = {}) {
  if (!Array.isArray(origins) || !Array.isArray(issues)) {
    return []
  }

  if (issues.length === 0) {
    return []
  }

  const originIssueMap = new Map(
    origins
      .filter(origin => typeof origin?.number === 'number')
      .map(origin => [origin.number, origin]),
  )

  return issues.map((category) => {
    const categoryIssues = Array.isArray(category?.issues) ? category.issues : []
    const normalizedIssueList = categoryIssues.map((issue) => {
      const originIssue = originIssueMap.get(issue?.number)
      return normalizeIssueDetail(issue, originIssue)
    })

    return {
      name: category?.name || '',
      issues: normalizedIssueList,
    }
  })
}

export function formatIssueForAI(rawBody) {
  if (!rawBody)
    return ''

  let cleaned = typeof rawBody === 'string' ? rawBody : String(rawBody)

  cleaned = cleaned.replace(HTML_COMMENT_REGEX, '')
  cleaned = cleaned.replace(MARKDOWN_IMAGE_REGEX, '[Image]')
  cleaned = cleaned.replace(HTML_IMAGE_REGEX, '[Image]')

  cleaned = cleaned.replace(CODE_BLOCK_REGEX, (match) => {
    const lines = match.split('\n')
    if (lines.length > 40) {
      const top = lines.slice(0, 15).join('\n')
      const bottom = lines.slice(-15).join('\n')
      return `${top}\n\n... [长代码/日志已截断 (Long Code/Logs Truncated)] ...\n\n${bottom}`
    }
    return match
  })

  cleaned = cleaned.replace(IGNORE_HEADER_SECTION_REGEX, '')
  cleaned = cleaned.replace(ISSUE_CHECKBOX_REGEX, '')
  cleaned = cleaned.replace(BOT_FOOTER_REGEX, '')
  cleaned = cleaned.replace(MULTIPLE_EMPTY_LINES_REGEX, '\n\n')
  cleaned = cleaned.replace(TRAILING_SPACES_REGEX, '')

  return cleaned.trim()
}
